addons:
  apt:
    packages:
      - gnupg2
matrix:
  include:
    - os: linux
      language: generic
      sudo: required
      dist: trusty

before_install: ./z/setup/bootstrap
script: ./z/ci/verify
